type T1 [int];
type T2 [int, string];
type T3 [int, int, int...];
type T4 [int, string, int...];
type T5 [int, string, string...];
type T6 [any];
type T7 [int, any];
type T8 [int, any...];
type T9 [any...];
type T10 [int...];
